# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f8915deeee4343874e855828fa2b770bd57294ead978cd0d5a65c8ba5ef881a335204de663277a2f75330892be261237bda2938671bbe23cbdf66d809803ebe2

test:
  secret_key_base: 17f849e1d7bd246b49267d3e78779cecc828061bdd76fe11cb5bbeeed26bba4ead3816e32cb18ae8195f885078c0cea1dd2dfb3704e57f13af620121321acb05

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
